version: "3.8"

services:
  fileserver:
    build:
      context: .
      target: build
    image: fileserver
    command: [ "npm", "run", "debug" ]
    ports:
      - ${NODE_PORT}:${NODE_PORT}
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
    env_file: .env

  minio:
    restart: always
    image: minio/minio:RELEASE.2022-07-17T15-43-14Z.fips
    volumes:
      - s3_data:/data
    command: minio server /data

  redis:
    restart: always
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file: .env

volumes:
  s3_data: null
  redis_data: null
